meta_product_name: "Yutags"
meta_title: "Tag your city!"
meta_description: "Find your city and change the name of your neighbourhood to something more accurate."
meta_image: "yutags-montreal.png"
twitter_account: "@colbol"
